# =============================================
# SERVIDOR
# =============================================
spring.application.name=techgear
server.port=8080

# =============================================
# POSTGRESQL - Base de datos local TechGear
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/TechGear
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / HIBERNATE
# Usamos "validate" para no tocar tus tablas existentes
# =============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# LOGGING
# =============================================
logging.level.com.techgear=DEBUG
